VoteApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin


app_name = "vote"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^", include("vote.urls")),

]

vote/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "vote"
urlpatterns = [
    url(r'^$', views.VotePage.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.QuestionDetail.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/vote$', views.vote, name='vote'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r"^(?P<pk>\d+)/results/api_get/$", views.ajax_get, name="ajax_get"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r'^login/$', LoginView.as_view(template_name="vote/login.html"), name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name="admin/base.html"), name='logout'),

]

vote/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
import datetime


class Judge(AbstractUser):
    votes = models.IntegerField("number of votes", default=1,)


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

vote/views.py
from django.views.generic import TemplateView, DetailView, ListView
from .models import Question, Choice
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.http import JsonResponse


class VotePage(ListView):
    """
    Top Page
    """
    template_name = "vote/index.html"
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published polls."""
        return Question.objects.order_by('-pub_date')[:5]

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        """ Login is required to view this page """
        return super(VotePage, self).dispatch(*args, **kwargs)


class ThanksPage(TemplateView):
    """
    Thanks Page For Vote
    """
    template_name = "vote/thanks.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        """ Login is required to view this page """
        return super(ThanksPage, self).dispatch(*args, **kwargs)


class QuestionDetail(DetailView):
    """

    """
    template_name = "vote/detial.html"
    model = Question

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(QuestionDetail, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["votes"] = self.request.user.votes
        return context


class ResultsView(DetailView):
    """
    Display the result of voting
    """
    model = Question
    template_name = 'vote/results.html'

    # Staff only
    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        """ Login is required to view this page """
        return super(ResultsView, self).dispatch(*args, **kwargs)


@login_required
def vote(request, pk):
    """
    This function is for　each user to vote.
    """
    if request.method == "POST":
        vote_counts = request.POST.getlist('choice')
        votes_sum = sum([int(vote_count) for vote_count in vote_counts])
        question = get_object_or_404(Question, pk=pk)
        if votes_sum == request.user.votes:
            for i, count in enumerate(vote_counts):
                pk = i + 1
                count = int(count)
                if count != 0:
                    try:
                        selected_choice = question.choice_set.get(pk=pk)
                    except (KeyError, Choice.DoesNotExist):
                        return render(request, "vote/detial.html", {
                            'question': question,
                            'error_message': "You didn't select a choice.",
                        })
                    else:
                        if count > 0:
                            selected_choice.votes += count
                            request.user.votes -= count
                            request.user.save()
                            selected_choice.save()
                        else:
                            print("Not enough")
                            return render(request, "vote/detial.html", {
                                'question': question,
                                'error_message': "You didn't select a choice.",
                            })

            print("ok")
            return render(request, "vote/thanks.html")
        else:
            print("Not enough")
            return render(request, "vote/detial.html", {
                'question': question,
                'error_message': "You didn't select a choice.",
            })

    else:
        redirect("vote:index")


def ajax_get(request, pk):
    """
    This fuction is for getting result of voting now by ajax.
    """
    if request.method == "GET":
        question = get_object_or_404(Question, pk=pk)
        choices = question.choice_set.all()
        choice_list = []
        for choice in choices:
            choice_contents = {
                "choice_text": choice.choice_text,
                "votes": choice.votes,
            }
            choice_list.append(choice_contents)

        choice_json = {
            "choice_list": choice_list
        }
        return JsonResponse(data=choice_json)

templates/vote/admin_base.html
{% extends "admin/base.html" %}

{% block title %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Vote App Login</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}

templates/vote/base.html
<!DOCTYPE html>
{% load staticfiles %}
<!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Custom CSS   -->
    <link rel="stylesheet" href="{% static "css/vote.css" %}" type="text/css" />
    <link rel="stylesheet" href="{% static "css/plusbutton.css" %}" type="text/css" />



    <!-- Social Footer, Colour Matching Icons -->
    <!-- Include Font Awesome Stylesheet in Header -->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>

    <script src="http://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Vote Page</title>
</head>


<body>
    {% block content %}

    {%  endblock %}

</body>
</html>

templates/vote/detial.html
{% extends "vote/base.html" %}
{% block content %}
    <div class="container text-center">
        <h1>Please choose what you think is the best</h1>
        <h1>{{ question.question_text }}</h1>
        {% if error_message %}<p style="color:red"><strong>{{ error_message }}</strong></p>{% endif %}
        <h1>The remaining <span id="remain-votes">{{ votes }}</span> votes</h1>
         <form id="vote-form" action="{% url 'vote:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
                <div>
                    <div class="col-xs-12 text-center choice-block">
                        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
                        <input style="border:none" size="4" maxlength="2" name="choice" id="choice{{ forloop.counter }}" value=0 />   票
                        <div class="button__holder">
                            <span id="choice{{ forloop.counter }}" class="plus" onclick="btnplusClick(this);"></span>
                            <span id="choice{{ forloop.counter }}" class="minus" onclick="btnminusClick(this);"></span>
                        </div>
                    </div>
                </div>
            {% endfor %}

            <div class="text-center">
                <div>
                    <p></p>
                </div>
                <input class="submit-button btn-success waves-effect" type="submit" value="Vote" />
            </div>
         </form>

    </div>

    <script type="text/javascript">
    var remain = parseInt( $('#remain-votes').text());
    var max = remain;

        function btnplusClick(this_obj){
            var $id =  $(this_obj).attr("id");
            var $value = $('#'+ $id).parent(".choice-block").find("input").val();
            if (remain !== 0){
                $value ++ ;
                remain --;
                $('#' + $id).parent(".choice-block").find("input").val($value);
                $('#remain-votes').text(remain);

            }
            else {
                alert("You can not vote any more")
            }


        }
        function btnminusClick(this_obj){
            var $id =  $(this_obj).attr("id");
            var $value = $('#'+ $id).parent(".choice-block").find("input").val();
            if ($value >  0 && remain < max){
                $value -- ;
                remain ++ ;
                $('#' + $id).parent(".choice-block").find("input").val($value);
                $('#remain-votes').text(remain);
            }
            else{
                alert("You can not reduce the number any more")
            }


        }
    </script>
{% endblock %}

templates/vote/index.html
{% extends "vote/base.html" %}
{% block content %}
    <div class="container">
        {% if latest_question_list %}
            <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'vote:detail' question.id %}">{{question.question_text }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No Question are available.</p>
        {% endif %}
    </div>
{% endblock %}

templates/vote/login.html
{% extends "vote/admin_base.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/login.css" %}" />
{{ form.media }}
{% endblock %}

{% block bodyclass %}{{ block.super }} login{% endblock %}

{% block usertools %}{% endblock %}

{% block nav-global %}{% endblock %}

{% block content_title %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
{% if form.errors and not form.non_field_errors %}
<p class="errornote">
{% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="errornote">
    {{ error }}
</p>
{% endfor %}
{% endif %}

<div id="content-main">

{% if user.is_authenticated %}
<p class="errornote">
{% blocktrans trimmed %}
    You are authenticated as {{ username }}, but are not authorized to
    access this page. Would you like to login to a different account?
{% endblocktrans %}
</p>
{% endif %}

<form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
  <div class="form-row">
    {{ form.username.errors }}
    {{ form.username.label_tag }} {{ form.username }}
  </div>
  <div class="form-row">
    {{ form.password.errors }}
    {{ form.password.label_tag }} {{ form.password }}
    <input type="hidden" name="next" value="{{ next }}" />
  </div>
  {% url 'admin_password_reset' as password_reset_url %}
  {% if password_reset_url %}
  <div class="password-reset-link">
    <a href="{{ password_reset_url }}">{% trans 'Forgotten your password or username?' %}</a>
  </div>
  {% endif %}
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="{% trans 'Log in' %}" />
  </div>
</form>

</div>
{% endblock %}

templates/vote/results.html
{% extends "vote/base.html" %}
{% block content %}
    <div>

    <div class="timer text-center">
        <div class="container text-center" id="result">
            <p id="timer">3</p>
            <p id="sec">sec</p>
        </div>

        <div class="buttons">
            <input type="button" id="start" value="Start" onclick="btnstratClick();">
            <input type="button" id="stop" value="Stop" onclick="btnstopClick();">
        </div>
    </div>
        {% for choice in question.choice_set.all %}
            <div class="choice-box" id="box{{ forloop.counter0 }}">
                <h1 id="choice{{ forloop.counter0 }}">{{ choice.choice_text }}</h1>
                <h2 id="votes{{ forloop.counter0 }}">{{ choice.votes }}</h2>
            </div>
        {% endfor %}
        <ul id="choice"></ul>

    </div>

<!-- Custom JS -->
    {% load static %}
    <script src="{% static "js/result.js" %}" type="application/javascript"></script>
{% endblock %}

templates/vote/thanks.html
{% extends "vote/base.html" %}
{% block content %}
    <h1>Thank you for Voting</h1>
{% endblock %}